name: Initial Index Creation

on:
  schedule:
    - cron: "*/5 * * * *"  # 매 분마다 실행

jobs:
  index-creator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t camelia9999/diningbuddy:initial-index -f mysql-to-es/initial-index.Dockerfile ./mysql-to-es
          docker push camelia9999/diningbuddy:initial-index

      - name: Deploy on OCI Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PUBLIC_IP }}       # OCI VM 인스턴스 퍼블릭 IP 주소
          username: ${{ secrets.HOST_USER_NAME }}                  # OCI 기본 유저명
          key: ${{ secrets.SSH_PRIVATE_KEY }} # GitHub Secrets에 저장한 프라이빗 키
          port: 22
          script: |
            # 기존 컨테이너 정리
            docker stop initial-index || true
            docker rm initial-index || true

            # 새 이미지 풀링 및 실행
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull camelia9999/diningbuddy:initial-index
            
            # 인덱스 생성 실행
            docker run --name initial-index \
              --network ubuntu_app-network \
              -e ELASTICSEARCH_HOST=es-singlenode \
              -e MYSQL_HOST=mysql \
              camelia9999/diningbuddy:initial-index