name: Initial Index Creation

on:
  workflow_run:
    workflows:
      - Restaurant DB Manager
    types:
      - completed

jobs:
  index-creator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t your-dockerhub-user/initial-index:latest .
          docker push your-dockerhub-user/initial-index:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker pull your-dockerhub-user/initial-index:latest
            docker run --rm your-dockerhub-user/initial-index:latest
