name: Restaurant DB Manager

on:
  push:
    branches:
      - main

jobs:
  db-manager:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t your-dockerhub-user/restaurant-db-manager:latest .
          docker push your-dockerhub-user/restaurant-db-manager:latest

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            docker pull your-dockerhub-user/restaurant-db-manager:latest
            docker run --rm your-dockerhub-user/restaurant-db-manager:latest
