name: Update Restaurant Ranks

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
  pull_request:
    branches: [ main ]

jobs:
  update-restaurant-ranks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./csv-to-mysql
          file: ./csv-to-mysql/restaurant-rank/update_restaurant_ranks.Dockerfile
          platforms: linux/amd64
          push: true
          tags: camelia9999/diningbuddy:update_restaurant_ranks

      - name: Deploy on OCI Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_PUBLIC_IP }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin
            # 기존 컨테이너 정리
            docker stop update_restaurant_ranks || true
            docker rm update_restaurant_ranks || true

            docker pull --platform linux/amd64 camelia9999/diningbuddy:update_restaurant_ranks

            docker run --platform linux/amd64 --name update_restaurant_ranks \
            --network ubuntu_app-network \
            -e MYSQL_HOST=${{ secrets.MYSQL_HOST }} \
            -e MYSQL_USER=${{ secrets.MYSQL_USER }} \
            -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
            -e MYSQL_DB=${{ secrets.MYSQL_DB }} \
            camelia9999/diningbuddy:update_restaurant_ranks